import fs from "node:fs";
import path from "node:path";
import process from "node:process";

function loadTemplate(lang) {
  const file = lang === "zh" ? "zh.md" : "en.md";
  const p = path.resolve(process.cwd(), "templates", file);

  // 优先读取项目根目录下的 templates
  if (fs.existsSync(p)) {
    return fs.readFileSync(p, "utf8");
  }

  // fallback：内置模板（理论上不会走到，保险用）
  return lang === "zh" ? defaultZh : defaultEn;
}

function render(template, data) {
  return template.replace(/\{\{(\w+)\}\}/g, (_, key) => {
    const value = data[key];

    if (Array.isArray(value)) {
      return value.map((item) => `- ${item}`).join("\n");
    }

    return value ?? "";
  });
}

export function generateReadme(data) {
  const template = loadTemplate(data.lang);
  const content = render(template, data).trim();

  return (
    content +
    "\n\n---\n" +
    "_Generated by ReadmeCraft_\n"
  );
}

// 内置兜底模板（极简）
const defaultEn = `# {{projectName}}

{{description}}

## Features
{{features}}

## Installation
\`\`\`bash
{{install}}
\`\`\`

## Usage
\`\`\`bash
{{usage}}
\`\`\`

## License
{{license}}
`;

const defaultZh = `# {{projectName}}

{{description}}

## 功能
{{features}}

## 安装
\`\`\`bash
{{install}}
\`\`\`

## 使用
\`\`\`bash
{{usage}}
\`\`\`

## 许可证
{{license}}
`;
